[build]
  command = "vite build"
  publish = "dist"

[context.production.environment]
  VITE_FIREBASE_API_KEY = "TU_API_KEY"
  VITE_FIREBASE_AUTH_DOMAIN = "web-flashstore.firebaseapp.com"
  VITE_FIREBASE_PROJECT_ID = "web-flashstore"
  VITE_FIREBASE_STORAGE_BUCKET = "web-flashstore.appspot.com"
  VITE_FIREBASE_MESSAGING_SENDER_ID = "182381546526"
  VITE_FIREBASE_APP_ID = "1:182381546526:web:b87ab6845e6619de94b20f"
  VITE_FIREBASE_MEASUREMENT_ID = "G-WLX4QWES7Z"
